app/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

students/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('app/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Student(models.Model):
    YEAR = (
        ('1', 'First'),
        ('2', 'Second'),
        ('3', 'Third'),
        ('4', 'Fourth'),
    )
    index = models.CharField(max_length = 12,primary_key=True)
    name = models.CharField(max_length = 20)
    surname = models.CharField(max_length = 20)
    email = models.CharField(max_length = 50)
    year = models.CharField(max_length = 1, choices = YEAR)
    def __str__(self):
        return self.index+" "+self.name+" "+self.surname

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from .models import Student
from django.http import Http404
from django.shortcuts import render,get_object_or_404
# from django.template import loader


def index(request):
    student_list = Student.objects.filter() #lepsi nacin?
    context = {'student_list':student_list}
    return render(request,'app/index.html',context)

    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {
    #     'latest_question_list': latest_question_list
    # }
    # return render(request, 'app/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'app/details.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

app/templates/app/details.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

app/templates/app/index.html
<!-- {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %} -->

{% if student_list %}
    <table style="width:100%"  border="2">
        <tr>
            <th>index</th>
            <th>ime</th>
            <th>prezime</th>
            <th>email</th>
            <th>year</th>
        </tr>
    {% for student in student_list %}
        <tr>
            <th>{{ student.index }}</th>
            <th>{{student.name}}</th>
            <th>{{ student.surname}}</th>
            <th>{{student.email}}</th>
            <th>{{student.year}}</th>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}